### PR TITLE
Added unicode support for ListDir

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@DigitMan27 If for any reason you want this pull request to be merged into `develop` instead of `master` just tell me and I will open a new pull request!

**Comment by ghost** [comment]
@DigitMan27 Let me know what you think.

**Comment by DigitMan27** [comment]
make new pr for the develop

**Comment by ghost** [comment]
@DigitMan27 ok!

**Comment by ghost** [comment]
I am closing this pr now

**Pull request closed without merging**
