### PR TITLE
independence about %username% and system drive and (UTF8 maybe :P)

### PR DESCRIPTION
**Pull request by DigitMan27**
Unicode does not supported. :(

### CODE REVIEW

**Comment by ghost** [comment]
@DigitMan27 Looks fine!

**Comment by ghost** [comment]
@DigitMan27 Why not use [FindFirstFileNameW](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364421(v=vs.85).aspx) and [FindNextFileNameW ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364429(v=vs.85).aspx) ?

**Comment by DigitMan27** [comment]
@xorz57 I did not use them because the [FindNextFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364428(v=vs.85).aspx) and [FindFirstFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364418(v=vs.85).aspx) search and for sub dir and returns and information about files. If u think that the above functions are more operating use them.

**Comment by ghost** [comment]
@DigitMan27 No you are not. You are using FindFirst**FileW** not FirstFirst**FileNameW** but that was not thr problem in the end 😆 .

**Comment by DigitMan27** [comment]
@xorz57 i forgot to put the W in the end of the word.shit happens :P :P

**Comment by xorz57** [comment]
What you wrote works fine but Unicode characters don't show up in the terminal. In order to fix this:
Add the following code segment at the beginning of the main function
```
#ifdef _WIN32
		_setmode(_fileno(stdout), _O_U16TEXT);
#endif
```
Add the following `includes` to Bragi.h
```
#include <fcntl.h>
	#include <io.h>
```

**Review by ghost — CHANGES_REQUESTED** [review]
@DigitMan27 What you wrote works fine but Unicode characters don't show up in the terminal. In order to fix this:
Add the following code segment at the beginning of the main function
```
#ifdef _WIN32
		_setmode(_fileno(stdout), _O_U16TEXT);
#endif
```
Add the following `includes` to Bragi.h
```
#include <fcntl.h>
#include <io.h>
```

After that, Unicode characters show up 😃 !!!!!!

**Comment by DigitMan27** [comment]
@xorz57  check that out!!!
(NOTE: I did not say tha unicode works fine... just saying :P)

**Review by ghost — APPROVED** [review]
Works great!

**Comment by ghost** [comment]
@DigitMan27 You can merge it now if you want.

**Pull request merged**
